services:
  app:
    build: .
    container_name: agentic-rag
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - pgvector

  pgvector:
    image: agnohq/pgvector:16
    container_name: pgvector
    ports:
      - "5532:5432"
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data

volumes:
  pgvolume:
